/**
 * This code was generated by @basketry/typescript-tests@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit ../../wealthvp/rest-api/src/schema.oas3.json
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://github.com/basketry/basketry/wiki
 * About @basketry/typescript-tests: https://github.com/basketry/typescript-tests#readme
 */

export function buildNewUser() {}
export function buildUserUpdate() {}
